# Generated by Django 2.2.6 on 2020-05-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='com_date',
            new_name='created',
        ),
    ]
